name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.preset }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: linux-debug
            triplet: x64-linux
          - os: macos-latest
            preset: macos-debug
            triplet: x64-osx
          - os: windows-latest
            preset: windows-debug
            triplet: x64-windows
          - os: windows-latest
            preset: windows-release
            triplet: x64-windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages (macOS)
        if: runner.os == 'macOS'
        run: brew install pkg-config ninja

      - name: Install system packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        shell: pwsh

      - name: Install vcpkg (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: .\vcpkg\vcpkg install --triplet=${{ matrix.triplet }}
        shell: pwsh

      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        run: ./vcpkg/vcpkg install --triplet=${{ matrix.triplet }}

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build out/build/${{ matrix.preset }} --config ${{ contains(matrix.preset, 'release') && 'Release' || 'Debug' }}

      - name: Install
        run: cmake --install out/build/${{ matrix.preset }} --prefix out/install/${{ matrix.preset }}

      - name: Package
        run: cpack --preset ${{ matrix.preset }}
        env:
          PACKAGE_NAME: "odin-protoc-plugin"
          PACKAGE_VERSION: ${{ github.ref_name }}
          PACKAGE_SYSTEM: ${{ matrix.preset }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: "out/build/${{ matrix.preset }}/package/*.zip"
          fail_on_unmatched_files: true
          generate_release_notes: true
